nombre = input("Nombre?")
apellido = input("Apellido?")
id1 = input("ID del producto")
id2 = input("ID del producto")
id3 = input("ID del producto")
id4 = input("ID del producto")
id5 = input("ID del producto")
nombre_del_producto1 = input("Nombre del producto")
nombre_del_producto2 = input("Nombre del producto")
nombre_del_producto3 = input("Nombre del producto")
nombre_del_producto4 = input("Nombre del producto")
nombre_del_producto5 = input("Nombre del producto")
monto_a_pagar1 = input("Monto del producto")
monto_a_pagar2 = input("Monto del producto")
monto_a_pagar3 = input("Monto del producto")
monto_a_pagar4 = input("Monto del producto")
monto_a_pagar5 = input("Monto del producto")
print("Registro contable de", nombre, apellido)
print("ID --- Descripción          Monto")
print(id1," --- ", nombre_del_producto1, "          --- ", monto_a_pagar1)
print(id2," --- ", nombre_del_producto2, "          --- ", monto_a_pagar2)
print(id3," --- ", nombre_del_producto3, "          --- ", monto_a_pagar3)
print(id4," --- ", nombre_del_producto4, "          --- ", monto_a_pagar4)
print(id5," --- ", nombre_del_producto5, "          --- ", monto_a_pagar5)